version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smile_classifier_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      - MYSQL_HOST=mysql_container
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=163801
      - MYSQL_DB=smiley

  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=163801
      - MYSQL_DATABASE=smiley
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
